name: Academicmaster
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 20.20.0+30

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  another_flushbar: ^1.10.8
  auto_route: ^0.6.9
  chewie: ^0.9.10
 
  cupertino_icons: ^0.1.3
  dartz: ^0.9.2
  flushbar: ^1.10.4
  flutter_bloc: ^6.1.2
  flutter_hooks: ^0.15.0
  flutter_local_notifications: ^1.3.0
  flutter_slidable: ^0.5.7
  fluttertoast: ^3.1.3
  
  freezed_annotation: ^0.12.0
  get: ^3.17.1
  get_it: ^4.0.4
  google_fonts: ^1.1.0
  google_sign_in: ^4.5.9
  http: ^0.12.0+4
  image_cropper: ^1.3.1
  image_picker: ^0.6.7+7
  implicitly_animated_reorderable_list: ^0.3.0
  injectable: ^1.0.7
  json_annotation: ^3.0.1
  kt_dart: ^0.8.0
  
  path_provider: ^1.6.11
  provider: ^4.3.3
  razorpay_flutter: ^1.2.2
  rxdart: ^0.24.1
  shared_preferences: ^0.5.7+1
  url_launcher: ^5.5.3
  uuid: ^2.2.2
  video_player: ^0.10.11+2
  youtube_player_flutter: ^7.0.0+7

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.6.10
  build_runner: ^1.11.1
  freezed: ^0.12.7
  injectable_generator: ^1.0.4
  json_serializable: ^3.3.0
  lint: ^1.3.0

flutter:

  uses-material-design: true
  assets:
    - images/

  fonts:
    - family: Dancing
      fonts:
        - asset: fonts/myfonts.ttf
